### ISSUE TITLE
Things to do Week 1

### ISSUE THREAD

**Issue by kammitama5** [CodingForProduct/metro_reward#1]
- Make sketch for app
       - what buttons do we need?
      - what sort of layout (affiliate businesses?)
      - who is our user
- Research apis
- Presentation layout

**Comment by niamurrell** [comment]
A bit farther down the line we can probably add content pages (affiliate business logos, how to earn points, etc.). For basic functionality & look/feel I think we are ready for initial presentations

**Comment by kammitama5** [comment]
Good point! We're all such a great team! :) 🙌
