### ISSUE TITLE
Persona : Who is our client

### ISSUE THREAD

**Issue by kammitama5** [CodingForProduct/metro_reward#2]
Type of user:
-Male/ Female
-Age
-Income
-Interests
- Motivation to use App

**Comment by niamurrell** [comment]
We could use the metro user Richard Snyder from the [LA Times article](http://www.latimes.com/local/lanow/la-me-ln-bus-ridership-study-20170518-story.html) as our persona? He is:

* Male age 32 lives in North Hollywood
* Occupation - video game tester, [$30-40k per year](http://howtobecomeagametester.com/average-video-game-tester-salary/)
* Metro history - used to commute 2 hours each way from Canoga Park to Torrance until he moved to North Hollywood to be closer to train service
* Interests - video games, tech gadgets, podcasts, burritos, pizza, beer
* Motivation to use app 
    * Taking metro anyway, may as well earn free stuff 
* Benefits from him using the app
    * Metro gains loyalty & mitigates negative sentiment about long wait times
    * Local businesses gain awareness, potentially a new customer, frequency of use while he waits for train/bus 
   * May provide discouragement from seeking alternatives (Uber/Lyft)
