### ISSUE TITLE
Week 2 presentation

### ISSUE THREAD

**Issue by kammitama5** [CodingForProduct/metro_reward#22]
Things to talk about: 

- Database:  Postgres instead of Firebase
- CSS Framework: Bootstrap.js
- Framework: Node.js 
- Add Dummy data (populate fake database)
- Project Management Tools: Github issues (most intuitive, already using : Projects has great Project Management tools)
- Continue working on UI (Bootstrap.js)

- Decided going with TAP card number as primary ID ??

**Comment by niamurrell** [comment]
Presented with flying colors
