### ISSUE TITLE
App/Product Name

### ISSUE THREAD

**Issue by niamurrell** [CodingForProduct/metro_reward#3]
## Potential Names for the app

* Rides for Rewards
* Tap for Treasure
* Treasure TAP (like treasure map)
* Rail Perks
* Perks Pass (Program)
* Go Go Gem Rewards (Gem themed..passengers collect different colored gems which correspond to 
  different tiers of rewards / points eg blue = 5 pts, purple = 25. Also gives treasure hunt theme = fun 
  inclusive of family (fun for children, etc))
* TAPmore
* Markdown (with the Metro M as the logo)
* Metro Medals

**Comment by niamurrell** [comment]
Any favorites from the list?

**Comment by kammitama5** [comment]
Let's stick with Rides for Rewards

**Comment by niamurrell** [comment]
Ok sounds good!

**Comment by kammitama5** [comment]
I'm also updating the READ.ME (feel free to jump in) so that we can do our presentation from there and hot-link to issues/ diagrams, etc.
