### ISSUE TITLE
Final Presentation 

### ISSUE THREAD

**Issue by kammitama5** [CodingForProduct/metro_reward#31]
Cover: 
1. One idea per slide-> Introduce Team
2. Audience: Metro as client 
3. Identify Problem -> Metro commuter population declining (Assumption)
4. Research -> What we did (briefly). Who is this for? Why would they use it? (Persona)
5. Prototyping -> (briefly) How did we start (diagrams, etc)
6. User Testing -> (did we do any?) What sort of feedback did we get?
7. Name of app -> Show how app works (talk briefly about pipeline, framework, database..easy to add and show data)
8. Show how it integrates into products they already have and why it helps them
9. Is the app maintainable or would it need updating in future releases/ improvements (full time vs temp 
   dev scenario)
10. Conclusion -> Does it improve quality of life, etc...

================================================================
1) your app solves a problem for a particular group of users
2) that you are someone Metro should hire as either an intern or full-time dev.

That way your presentation needs to cover both the product side and the techinical coding side"

**Comment by niamurrell** [comment]
Thanks for putting this together, it looks great!

**Comment by kammitama5** [comment]
done
