### ISSUE TITLE
Affiliate Businesses (local businesses or corporate)

### ISSUE THREAD

**Issue by kammitama5** [CodingForProduct/metro_reward#4]
- What kind of businesses would be interested?

- Local
- Corporate 

- Local more likely to have discounts. 
  Would it include public places like Library or Iconic places like Amoeba discounts?
- Iconic LA, so incentive tied to iconic parts of LA:
  eg. discounted or free ticket to Arclight
- Griffith Park Observatory Planetarium ticket
- Pink's Hotdog free
- Some already exist like Universal Affiliate programs

- Seasonal deals (some already exist) for Christmas, Halloween, New Year, etc

**Comment by kammitama5** [comment]
**Local Businesses**
- Golden Road Brewery
- Pink's Hot Dog

**Corporate/ Larger:**

- Chipotle
- In-N-Out Burger
- Ralph's 
- Carl's Jr
- Domino's Pizza

**Comment by niamurrell** [comment]
added a few to your list

**Comment by kammitama5** [comment]
Great! These are great! Keep 'em coming if you think of any more :)
