### ISSUE TITLE
Sketch App Functionality

### ISSUE THREAD

**Issue by niamurrell** [CodingForProduct/metro_reward#6]
Sketch is editable via [link](https://docs.google.com/drawings/d/1vkzyW_OL4gnj_eXuF-hKhmT2hZ4GH_lieQfoQ_qLeDQ/edit?usp=sharing) on Google docs...feel free to play around with it

![metro rewards wireframe](https://user-images.githubusercontent.com/22780428/27615978-159a541a-5b61-11e7-8c66-7e8415c18c26.jpg)

**Comment by niamurrell** [comment]
**V2:**

![metro rewards wireframe v2](https://user-images.githubusercontent.com/22780428/27750939-e768b5e8-5d8e-11e7-992f-aec599479b25.png)

**Comment by kammitama5** [comment]
This is excellent! Thank you! Think we're all set for Sunday?

**Comment by niamurrell** [comment]
We just need to finalize the product name and our team name then I think we're ready!

**Comment by kammitama5** [comment]
Okey doke. Agreed!

**Comment by niamurrell** [comment]
Added red boxes around behaviors to indicate which ones are actual pages in the UI 

![metro rewards wireframe v3](https://user-images.githubusercontent.com/22780428/27877656-5b3ac666-6170-11e7-9aea-46901d888dda.png)

**Comment by niamurrell** [comment]
Now added v4 to include home page!

![metro rewards wireframe v4](https://user-images.githubusercontent.com/22780428/27877991-96e77bea-6171-11e7-86e8-240289f2658d.png)
