### ISSUE TITLE
Things to complete by 7/2/17

### ISSUE THREAD

**Issue by kammitama5** [CodingForProduct/metro_reward#7]
Presentation components : 
- [ ] name of group
- [x] name of team members 
- [x] name of the app
- [x] a Persona which describes the problem your app is trying to solve
- [x] sketches, wireframes, or Invision app of the main user flows of the app

**Comment by kammitama5** [comment]
I think we're pretty much done with this, although we do need a proper name of the App. Once we decide on a name, perhaps we can get all the information in one place for presentation (maybe on a Google docs or whatever for presentation)

**Comment by niamurrell** [comment]
Agree, sounds good
