### ISSUE TITLE
Phone Functionality UI

### ISSUE THREAD

**Issue by kammitama5** [CodingForProduct/metro_reward#8]
**First Look** 
![iphone_classic](https://user-images.githubusercontent.com/8516378/27664869-c1ede9e4-5c1e-11e7-91e3-7e17ff4e8a64.png)

**Sign Up**
![iphone6_signup_final2](https://user-images.githubusercontent.com/8516378/27697252-8d3a5ba8-5ca8-11e7-838a-5943377cccfc.png)

**Sign-In existing User Dashboard**

![iphone6_signinexistinguser2](https://user-images.githubusercontent.com/8516378/27697267-950879b4-5ca8-11e7-9b36-d24fdf468bfc.png)

**Cash Out**

![iphone6_cashout2](https://user-images.githubusercontent.com/8516378/27697279-9b31d84e-5ca8-11e7-9882-cf41c38b38ee.png)

**Comment by niamurrell** [comment]
This looks awesome, nice work!!

**Comment by kammitama5** [comment]
Thanks! I forgot to add a back button! I'll do that tomorrow 😆

**Comment by niamurrell** [comment]
sounds good, I'll simplify the functionality map to match this tomorrow too

**Comment by badickens** [comment]
It's good a great look and feel so far...to the point. Cool.

**Comment by kammitama5** [comment]
added a back button and slider option for the cash-out option.
